In [1]:
import numpy as np

np.random.seed(0) # seed for reproducibility

x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3,4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5),dtype=np.int64) # Three-dimensional array


In [2]:
#print(x3, "\n")
print ("x3 ndim: ", x3.ndim)
print ("x3 shape: ", x3.shape)
print ("x3 size: ", x3.size)
print ("dtype: ", x3.dtype)

print ("itemsize :", x3.itemsize, "bytes")
print ("nbytes :", x3.nbytes, "bytes")

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
dtype:  int64
itemsize : 8 bytes
nbytes : 480 bytes


In [41]:
# Array indexing: Accessing Single Elements
print (x1, "\n")
print ("First index element in array is", x1[0])
 
print ("Last index element in array is:", x1[-1])
print ("Starting three index elements in the array are:", x1[0:3])

[5 0 3 3 7 9] 

First index element in array is 5
Last index element in array is: 9
Starting three index elements in the array are: [5 0 3]


In [52]:
# Array indexing: For multi-dimensional arrays
print (x2, "\n")

print ("The first array element is :", x2[0,0])
print ("The second array element is :", x2[0,1])
print ("The second array element in second row of array is :", x2[1,1])

x2[0][0] = 12

print ("The array after modification is : \n", x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]] 

The first array element is : 3
The second array element is : 5
The second array element in second row of array is : 6
The array after modification is : 
 [[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [67]:
# Array slicing: Accessing sub arrays

x = np.arange(0,10)

print ("Array elements are :", x)

# first five elements
print ("First five elements of the array are :", x[:5])

# elements after index 5
print ("Elements after index 5 are :", x[5:])

# middle sub array
print ("Middle array elements are :", x[4:7])

# every other element
print ("Every other element in the array :", x[::2])

# every other element in array starting at index 1
print ("Every array element starting at index 1 are :", x[1::2])

# A potentially confusing case is when the step value is negative. Defaults to start and stop are swapped. 
print ("All elements reversed of the array :", x[::-1])

# Reversed every other from index 5
print ("elements reversed from index 5 :", x[5::-2])

Array elements are : [0 1 2 3 4 5 6 7 8 9]
First five elements of the array are : [0 1 2 3 4]
Elements after index 5 are : [5 6 7 8 9]
Middle array elements are : [4 5 6]
Every other element in the array : [0 2 4 6 8]
Every array element starting at index 1 are : [1 3 5 7 9]
All elements reversed of the array : [9 8 7 6 5 4 3 2 1 0]
elements reversed from index 5 : [5 3 1]


In [106]:
# Multidimensional subarrays
print ("The array elements are :\n", x2)

# two rows three columns
print (" \nTwo rows three columns")
print (x2[:2,:3])

# all rows, every other column
print ("\nAll rows, every other column")
print (x2[:3,::2])

# reversing subarray dimensions
print ("\nReversing subarray dimensions")
print (x2[::-1,::-1])

# first column on x2
print ("\nFirst column of array")
print (x2[:,0])

print ("\nFirst row of array :", x2[0,:])

print ("\nEquivalent to x2[0,:] is ", x2[0])

The array elements are :
 [[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
 
Two rows three columns
[[12  5  2]
 [ 7  6  8]]

All rows, every other column
[[12  2]
 [ 7  8]
 [ 1  7]]

Reversing subarray dimensions
[[ 7  7  6  1]
 [ 8  8  6  7]
 [ 4  2  5 12]]

First column of array
[12  7  1]

First row of array : [12  5  2  4]

Equivalent to x2[0,:] is  [12  5  2  4]


In [112]:
# sub arrays as no-copy views 
print (x2)

# extract 2x2 subarray from this
x2_sub = x2[:2,:2]
print ("\n The 2x2 sub array is :\n", x2_sub)

# modify the subarray and see the original array i.e. x2 is changed. Unlike Python arrays which are copies the 
# NumPy arrays are views

x2_sub[0][0] = 99

print ("\n The updated array structure is :\n", x2)


[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]

 The 2x2 sub array is :
 [[99  5]
 [ 7  6]]

 The updated array structure is :
 [[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [117]:
# creating copies of arrays using copy() function

x2_sub_copy = x2[:2,:2].copy()

print(x2_sub_copy)

# try to modify the element of the copied subarray
x2_sub_copy[0][0] = 42

print ("\n The copied sub array after the change :\n", x2_sub_copy)

print ("\n The original array after the change : \n", x2)

[[99  5]
 [ 7  6]]

 The copied sub array after the change :
 [[42  5]
 [ 7  6]]

 The original array after the change : 
 [[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
